# Generated by Django 3.0.5 on 2020-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='pid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
