# Generated by Django 3.0.5 on 2020-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pricing_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
