# Generated by Django 3.0.5 on 2020-06-18 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200618_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pro_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 9, 1, 14, 39922, tzinfo=utc)),
        ),
    ]
