# Generated by Django 3.0.5 on 2020-06-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200618_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pro_created',
        ),
    ]
