# Generated by Django 3.0.5 on 2020-06-19 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_subscription_pro_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Subscription_status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='approved_user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pro_user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='samay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
