# Generated by Django 3.0.5 on 2020-06-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200619_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-added_date']},
        ),
    ]
